### ISSUE TITLE
how about other "bad" cases?

### ISSUE THREAD

**Issue by redguy666** [javadelight/delight-nashorn-sandbox#1]
...like:

while(true);

or:

while(true) x++;

does your sandbox handle those as well? I noticed you add function checking for thread interruption on every ";" and every ") {" but none of this will work in cases above...

**Comment by mxro** [comment]
Good point. I added two more test cases with the examples you have given in [TestLimitCPU](https://github.com/javadelight/delight-nashorn-sandbox/blob/master/src/test/xtend/delight/nashornsandbox/tests/TestLimitCPU.xtend).

The tests still terminate since there is a 'monitoring' thread which checks the overall runtime of the script and then shuts the thread running the script down forcefully. This is not as graceful as using the interjected interruption code. Could you think of a better solution for interjecting the code?

    beautifiedJs.replaceAll(';\\n', ';intCheckForInterruption' + randomToken + '();\n').
							replace(') {', ') {intCheckForInterruption' + randomToken + '();\n')

**Comment by artfiedler** [comment]
Also there might be a way in jdk8 with implementing a "prepscript" anytime the user modifies their source code, parse it using jdk.nashorn.internal.parser.Parser (see: http://stackoverflow.com/questions/6511556/javascript-parser-for-java/24306346#24306346) and work through the resulting objects to emit a new source script, then save that output for later use and execute that generated version. OpenJDK source code is also available (including jdk9) here: https://wiki.openjdk.java.net/display/Nashorn/Building+Nashorn

In jdk9, there will be a Parser API for nashorn, possibly be able to inject the interrupt check more efficiently using the AST Nodes and visitor pattern, but depending on how that is handled it might still be ideal to do the prep so it doesn't have to be inspected every time the code is ran.

I think checking for interrupt every statement is very excessive and can have an impact on performance. I didn't think this out fully but the places I would put the check is the first line in a while, for, do, label-blocks(foo: { break foo; }) and function(recursion) blocks. JavaScript supports break & continue labels so if your not aware of how they are used take a look here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label

**Comment by mxro** [comment]
Thank you for your post and ideas.

So you think it should be possible to to parse the whole script beforehand and then inject the interrupt statements with more precision? That sounds very interesting. But in the JDK 9 API there would be a more efficient option.

I must say I am most concerned about keeping the sandbox secure rather than its performance. Do you think this could have any security advantages?

Regarding the label statements, I think this should be handled sufficiently at the moment. If you have an example where the sandbox does not work, please let me know!
