### ISSUE TITLE
Questions about throwing InterruptedException and why it is needed

### ISSUE THREAD

**Issue by DaniilRoman** [javadelight/delight-nashorn-sandbox#113]
I cannot understand purposes for throwing InterruptedException if we exceed our restrictions. https://github.com/javadelight/delight-nashorn-sandbox/blob/master/src/main/java/delight/nashornsandbox/internal/InterruptTest.java

Because I checked without it and throwing ScriptCPUAbuseException also interrupted our execution.
So it looks like it doesn't need but it can slow down our code execution because we invoke this method in js loops for example.
Can you please explain maybe I mixed something up?

**Comment by mxro** [comment]
It has been a while since I looked into this but I think ultimately this is to be able to more efficiently stop scripts that are using too much CPU, especially if no executor is set for the sandbox. When running the test suite with throwing this exception being commented out, there will be more instances of 'Thread hard shutdown' and one test case will also fail.

![image](https://user-images.githubusercontent.com/1448524/116680866-8e9f1400-a9ef-11eb-9981-3dac581bbd5f.png)

That being said, there may be scenarios when this is not required (e.g. when we are fine with threads being shut down ungracefully (`Hard shutdown`) and using executors for running the scripts. How much of an performance impact from this did you notice?

**Comment by DaniilRoman** [comment]
Yes, thanks a lot. For my case it really looks like not necessary so it cause why I asked this question.

I checked a performance and honestly performance changes are not so big. For my test is just about 5% degradation. I think it can be and less. It doesn't see as a trouble. 

Thanks again. Question can be closed.

**Comment by mxro** [comment]
That's great! Thanks for checking the performance impact @DaniilRoman. That's good to know! Will close this issue now!
