### ISSUE TITLE
`Array.from` support

### ISSUE THREAD

**Issue by lukehutch** [javadelight/delight-nashorn-sandbox#166]
Nashorn 15.4 is supposed to have `Array.from` support, according to:

https://github.com/efwGrp/nashorn-ext-for-es6

However, even if I call `NashornSandboxes.create("--language=es6")`, if I try to use this I get:

```
Array.from is not a function
```

I am depending on Nashorn 15.4 transiently:

```
[INFO] +- org.javadelight:delight-nashorn-sandbox:jar:0.5.0:compile
[INFO] |  +- org.webjars.npm:js-beautify:jar:1.14.7:compile
[INFO] |  \- org.openjdk.nashorn:nashorn-core:jar:15.4:compile
[INFO] |     +- org.ow2.asm:asm:jar:7.3.1:compile
[INFO] |     +- org.ow2.asm:asm-commons:jar:7.3.1:compile
[INFO] |     |  \- org.ow2.asm:asm-analysis:jar:7.3.1:compile
[INFO] |     +- org.ow2.asm:asm-tree:jar:7.3.1:compile
[INFO] |     \- org.ow2.asm:asm-util:jar:7.3.1:compile
```

**Comment by mxro** [comment]
Thank you for raising this issue as well.

I don't think `Array.from` is included in Nashorn - see for further information here: https://github.com/efwGrp/nashorn-ext-for-es6/blob/main/README.md

I think the easiest is to load a polyfill directly into the sandbox. I tried with above library as well, but it didn't seem to work well in the sandbox environment.

Here an example for adding the Array.from polyfill.

https://github.com/javadelight/delight-nashorn-sandbox/pull/167/files#diff-b949512a1f65eb8926a4d72edf7f72e7ad42c2d30a49b2ed99e51bf04cf0dae7

**Comment by lukehutch** [comment]
That's the same doc I linked. It says:

> The Array.from() static method creates a new, shallow-copied Array instance from an iterable or array-like object. nashorn15.4 is required.

So unless this doc is wrong, Nashorn 15.4 should support this.

**Comment by mxro** [comment]
Oh, I understood the document to list the methods that are included in the polyfill.

I tried the following in Vanilla Nashorn

```
		ScriptEngine scriptEngine = new ScriptEngineManager().getEngineByName("nashorn");
		try {
			scriptEngine.eval("Array.from(1,2,3)");
		} catch (ScriptException e) {
			throw new RuntimeException(e);
		}

```

And getting the same exception: `Caused by: javax.script.ScriptException: TypeError: Array.from is not a function in <eval> at line number 1`

So I assume the polyfill references Nashorn 15.4 as the Nashorn version required for the polyfill to work? That's how I would interpret the definition in code as well: https://github.com/efwGrp/nashorn-ext-for-es6/blob/main/dist/nashorn-ext-for-es6.js#L579 but could be wrong!

Are you able to use Array.from in vanilla Nashorn (maybe I didn't instantiate it right)? Would otherwise the polyfill work?

**Comment by lukehutch** [comment]
Ah! You had it right all along. I thought that page was saying Nashorn implemented these, not that the polyfill implemented them. I didn't read closely enough.

I appreciate your responsiveness. I'll close this, since it's not a sandbox problem. Thanks!
