### ISSUE TITLE
Memory usage falsely triggering

### ISSUE THREAD

**Issue by everestbt** [javadelight/delight-nashorn-sandbox#86]
The memory monitoring seems to trigger falsely, over long periods of use, when bindings are used.

The following test fails quickly:

``` java
@Test
public void testContinuedUse() throws Exception {
    final NashornSandbox sandbox = NashornSandboxes.create();
    sandbox.setMaxMemory(1024 * 2000);
    sandbox.setExecutor(Executors.newSingleThreadExecutor());
    try {
        final String js = "var o={},i=0; while (i < 10000) {o[i++] = 'abc'}";
        while (true) {
            Bindings bindings = sandbox.createBindings();
            bindings.put("a", "b");
            sandbox.eval(js, bindings);
        }
    }
    catch(final ScriptMemoryAbuseException e){
        fail();
    }
    finally {
        sandbox.getExecutor().shutdown();
    }
}
```

Each individual run of the script is fine, and there should not be any carry over between the runs, however when bindings are adjusted prior to running then this fails after ~16 runs of the script. 

Note if the line `bindings.put("a", "b");` is removed then this test will just hang forever (I need to add a stopwatch terminate or a max number of runs to make it a valid test). 

I have not yet been able to identify the cause of this, but wanted to field whether I am employing this incorrectly and whether anyone has any thoughts.

Note that this does seem sensitive to the amount of memory, upping the limit to `sandbox.setMaxMemory(1024 * 3000);` also seems to see the issue resolved. This could just be a memory amount issue but the amount change seems excessive here.

Also if you want the max amount of memory that the monitor is detecting it does steadily rise with time (just add a static variable for the max memory ever seen by the monitor and have it print on update).

**Comment by mxro** [comment]
@everestbt Please see the added unit tests.

Please note:

- When setting the memory to `1024 * 2000` and the iterations for the loop in Java to `100` the test _sometimes_ fails and sometimes succeeds. 
- It seems to never fail with `1024 * 4000` and iterations in Java loop to `1000` or even `1000` (Interestingly on my local machine it worked with `1024 * 3000` but it would fail with that in the CI environment, so I bumped it up to `1024 * 4000`)
- When moving the `Bindings bindings = sandbox.createBindings();` out of the loop it seems to never fail
- I dug around a bit but couldn't find any way in which the bindings reference could be held by the sandbox and thus leak memory. I verified the bindings object passed to the engine stays the same.

All in all I think this might behaviour might be caused by some weird things happening in Nashorn - eg what it does when createBindings is called and bindings are passed when executing the JS.

What do you think?

**Comment by everestbt** [comment]
@mxro I think that is exactly right.

So the memory needs to be quite generous when using bindings, double what one might expect. Do you think it is worth adding a statement to this effect on the `setMaxMemory` javadoc?

**Comment by mxro** [comment]
Good idea! Done!

**Comment by everestbt** [comment]
Apologies i never responded on this, closing the issue
